name: Terraform

on:
  workflow_dispatch:
  
env:
  AWS_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_region: 'us-east-1'
  
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsRole
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
    
      - name: Print message
        run: echo "Terraform workflow started!"

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
